In [2]:
import numpy as np

In [2]:
lst1  = [1234, 4567, 1343, 1224, 1454]

In [3]:
arr = np.array(lst1)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1234 4567 1343 1224 1454]


In [4]:
print(arr.shape)

(5,)


In [5]:
list1 = [534, 543, 874, 125, 812]
list2 = [453, 325, 264, 258, 287]
list3 = [998, 894, 345, 248, 934]


arr1 = np.array([list1, list2, list3])

print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[[534 543 874 125 812]
 [453 325 264 258 287]
 [998 894 345 248 934]]


In [6]:
print(arr1.shape)

(3, 5)


In [7]:
arr1.reshape(5,3)

array([[534, 543, 874],
       [125, 812, 453],
       [325, 264, 258],
       [287, 998, 894],
       [345, 248, 934]])

In [8]:
import array

In [9]:
arr = array.array('i', [101,102,103,104,105])
print(arr[2])

103


In [10]:
for i in arr:
    print(i)

101
102
103
104
105


In [11]:
for i in range(len(arr)):
    print('Index no:', i,'Element:', arr[i])

Index no: 0 Element: 101
Index no: 1 Element: 102
Index no: 2 Element: 103
Index no: 3 Element: 104
Index no: 4 Element: 105


In [12]:
n = len(arr)
i = 0
while i<n:
    print(arr[i])
    i += 1

101
102
103
104
105


In [13]:
arr.append(106)
print(arr)

array('i', [101, 102, 103, 104, 105, 106])


In [14]:
arr1 = array.array('i', [])

n = int(input("Enter the no. of elements: "))

for i in range(n):
    e = int(input("Enter the elements: "))
    arr1.append(e)

print("Your Final Array is:", arr1)

Enter the no. of elements: 3
Enter the elements: 101
Enter the elements: 102
Enter the elements: 103
Your Final Array is: array('i', [101, 102, 103])


In [15]:
n = int(input("Enter the no. of elements: "))

i = 0
while i < n:
    e = int(input("Enter the element: "))
    arr1.append(e)
    i += 1
    
print("Your Final Array is:", arr1)

Enter the no. of elements: 3
Enter the element: 101
Enter the element: 10203
Enter the element: 102
Your Final Array is: array('i', [101, 102, 103, 101, 10203, 102])


In [16]:
nparr = np.array([101,102,103,104,105])

for i in range(len(nparr)):
    print('Index no:', i,'Element:', nparr[i])

Index no: 0 Element: 101
Index no: 1 Element: 102
Index no: 2 Element: 103
Index no: 3 Element: 104
Index no: 4 Element: 105


In [17]:
lsarr = np.linspace(1, 10, 5, dtype='int')
print(lsarr)

[ 1  3  5  7 10]


In [20]:
narr = np.zeros(n, dtype=int)
x = int(input("Enter no. of elements: "))

for i in range(x):
    e = int(input("Enter the element: "))
    narr[i] = e

print("Your array is: ", narr)

Enter no. of elements: 5
Enter the element: 101
Enter the element: 102
Enter the element: 103
Enter the element: 104
Enter the element: 105
Your array is:  [101 102 103 104 105]


In [3]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

c = a+b
print(c)

[2 4 6 8]


In [4]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

c = a-b
print(c)

[0 0 0 0]


In [5]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

c = a*b
print(c)

[ 1  4  9 16]
