In [1]:
import numpy as np

In [2]:
lst1  = [1234, 4567, 1343, 1224, 1454]

In [3]:
arr = np.array(lst1)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1234 4567 1343 1224 1454]


In [4]:
print(arr.shape)

(5,)


In [5]:
list1 = [534, 543, 874, 125, 812]
list2 = [453, 325, 264, 258, 287]
list3 = [998, 894, 345, 248, 934]


arr1 = np.array([list1, list2, list3])

print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[[534 543 874 125 812]
 [453 325 264 258 287]
 [998 894 345 248 934]]


In [6]:
print(arr1.shape)

(3, 5)


In [7]:
arr1.reshape(5,3)

array([[534, 543, 874],
       [125, 812, 453],
       [325, 264, 258],
       [287, 998, 894],
       [345, 248, 934]])

In [8]:
import array

In [9]:
arr = array.array('i', [101,102,103,104,105])
print(arr[2])

103


In [10]:
for i in arr:
    print(i)

101
102
103
104
105


In [11]:
for i in range(len(arr)):
    print('Index no:', i,'Element:', arr[i])

Index no: 0 Element: 101
Index no: 1 Element: 102
Index no: 2 Element: 103
Index no: 3 Element: 104
Index no: 4 Element: 105


In [12]:
n = len(arr)
i = 0
while i<n:
    print(arr[i])
    i += 1

101
102
103
104
105


In [13]:
arr.append(106)
print(arr)

array('i', [101, 102, 103, 104, 105, 106])


In [14]:
arr1 = array.array('i', [])

n = int(input("Enter the no. of elements: "))

for i in range(n):
    e = int(input("Enter the elements: "))
    arr1.append(e)

print("Your Final Array is:", arr1)

Enter the no. of elements: 5
Enter the elements: 101
Enter the elements: 102
Enter the elements: 103
Enter the elements: 104
Enter the elements: 105
Your Final Array is: array('i', [101, 102, 103, 104, 105])


In [15]:
n = int(input("Enter the no. of elements: "))

i = 0
while i < n:
    e = int(input("Enter the element: "))
    arr1.append(e)
    i += 1
    
print("Your Final Array is:", arr1)

Enter the no. of elements: 5
Enter the element: 101
Enter the element: 102
Enter the element: 103
Enter the element: 104
Enter the element: 105
Your Final Array is: array('i', [101, 102, 103, 104, 105, 101, 102, 103, 104, 105])


In [16]:
nparr = np.array([101,102,103,104,105])

for i in range(len(nparr)):
    print('Index no:', i,'Element:', nparr[i])

Index no: 0 Element: 101
Index no: 1 Element: 102
Index no: 2 Element: 103
Index no: 3 Element: 104
Index no: 4 Element: 105


In [17]:
lsarr = np.linspace(1, 10, 5, dtype='int')
print(lsarr)

[ 1  3  5  7 10]


In [18]:
narr = np.zeros(n, dtype=int)
x = int(input("Enter no. of elements: "))

for i in range(x):
    e = int(input("Enter the element: "))
    narr[i] = e

print("Your array is: ", narr)

Enter no. of elements: 5
Enter the element: 101
Enter the element: 102
Enter the element: 103
Enter the element: 104
Enter the element: 105
Your array is:  [101 102 103 104 105]


In [19]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

c = a+b
print(c)

[2 4 6 8]


In [20]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

c = a-b
print(c)

[0 0 0 0]


In [21]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

c = a*b
print(c)

[ 1  4  9 16]


In [22]:
nparray = np.array([[1,2,3],[4,5.,6],[7,8,9],[10,11,12]], dtype='int')
nparray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
nparray.size

12

In [24]:
nparray.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
nparray.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [26]:
nparray.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [27]:
nparray.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [28]:
array_1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
array_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [29]:
array_a = array_1.reshape(2,8)
array_a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [30]:
array_1.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [31]:
print(array_1[0,3])
print(array_1[2,2])
print(array_1[0,-1])
print(array_1[2,-2])

4
11
4
11


In [32]:
print(array_1[:,1])

[ 2  6 10 14]


In [33]:
array_2 = np.zeros((3,3))
array_2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
arr1 = np.ones((3,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
arr2 = np.full((3,3),5)
arr2

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [36]:
arr3 = np.random.random((3,3))
arr3

array([[0.9427152 , 0.23885311, 0.65975185],
       [0.9051284 , 0.5991006 , 0.56765913],
       [0.7800897 , 0.76614599, 0.63046915]])

In [37]:
row_1 = [1,2,3,4,5]
row_2 = [6,7,8,9,10]
row_3 = [11,12,13,14,15]
row_4 = [16,17,18,19,20]
row_5 = [21,22,23,24,25]

In [38]:
arr_a = np.array([row_1,row_2,row_3,row_4,row_5])
arr_a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
print(arr_a[:,2:4])

[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


In [40]:
greater_than_ten = arr_a > 10
greater_than_ten

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [41]:
print(arr_a[greater_than_ten])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [42]:
drop_under_10 = np.where(arr_a > 10, arr_a, 0)
drop_under_10

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [43]:
drop_under_10_and_20 = np.logical_and(arr_a > 10, arr_a < 20)
drop_under_10_and_20

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [False, False, False, False, False]])

In [44]:
print(arr_a[drop_under_10_and_20])

[11 12 13 14 15 16 17 18 19]


In [45]:
sam_arr = np.arange(0, 100, 5)
sam_arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [46]:
print(sam_arr.size)
sam_arr_reshape = sam_arr.reshape((4,5))
sam_arr_reshape

20


array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [47]:
print(sam_arr_reshape[:,-1])

[20 45 70 95]


In [48]:
array_above_50 = np.where(sam_arr_reshape> 50, sam_arr_reshape, 0)
array_above_50

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [49]:
array_above_50 = sam_arr_reshape[sam_arr_reshape > 50]
array_above_50

array([55, 60, 65, 70, 75, 80, 85, 90, 95])

In [50]:
array_above_50 = sam_arr_reshape[sam_arr_reshape >= 50]
array_above_50

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [51]:
print(array_above_50[0:len(array_above_50):2])

[50 60 70 80 90]


In [52]:
print(sam_arr_reshape[:, 0:5:2])

[[ 0 10 20]
 [25 35 45]
 [50 60 70]
 [75 85 95]]


In [53]:
print(np.where(sam_arr_reshape>50, sam_arr_reshape, -1))

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 55 60 65 70]
 [75 80 85 90 95]]


In [54]:
print(np.where(sam_arr_reshape>50, sam_arr_reshape*2, -1))

[[ -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1]
 [ -1 110 120 130 140]
 [150 160 170 180 190]]


In [55]:
array_b = np.array([[1,1,1,1], [2,2,2,2], [3,3,3,3]])
array_c = np.array([0,1,2,3])
array_d = np.array([[1], [2], [3]])